import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import { RunningText } from "@/components/animation/RunningText";
import Footer from "@/components/Footer";

const font = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Komisi Pemilihan Umum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        {/* Mobile Running Text */}
        <div className="relative w-screen overflow-hidden lg:hidden">
          <RunningText>
            <p className=" whitespace-nowrap text-sm">
              Ingat.. Ayoo ke TPS !! Pemilu Serentak, Rabu 14 Februari 2024...
              Pemilu Sarana Integrasi Bangsa
            </p>
          </RunningText>
        </div>
        <main className=" px-5 mb-16 ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
